### ISSUE TITLE
"TransferCommodity" transaction not working

### ISSUE THREAD

**Issue by anilkharabe** [aprilsnows/hyperledger-composer-supply-chain-network#10]
Throws an error while submitting the "TranferCommodity" transaction.
![screenshot from 2018-05-03 12-13-17](https://user-images.githubusercontent.com/34509590/39562911-aa601108-4ecb-11e8-8088-7f9f3fb8fecd.png)

t: Instance org.hcsc.network.Commodity#ts1 has property company with type org.hyperledger.composer.system.NetworkAdmin that is not derived from org.hcsc.network.TraderA

**Comment by kapishps** [comment]
This is not an Issue. You were trying to transfer commodity with role of admin. Only Commodity Owner can Transfer the commodity.

**Comment by prabhuashwin** [comment]
So do we need to create new identities for the same i.e. Commodity Owner and then do this activity, do throw some light on this would help a lot.

**Comment by kapishps** [comment]
Yes, You need to create new id and then you can transfer commodity using that id.
